export const GET_MEDICINES_PAGINATION = "/medicines"
export const CREATE_MEDICINE = "/medicines"
export const UPDATE_MEDICINE = "/medicines"
export const DELETE_MEDICINE = "/medicines"
export const GET_MEDICINE_UNITS = "medicines/units"
